// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"

	"github.com/rodrigocavalhero/clean_arch_orders_list/internal/infra/database"
	"github.com/rodrigocavalhero/clean_arch_orders_list/internal/infra/web"
	"github.com/rodrigocavalhero/clean_arch_orders_list/internal/usecase"
)

func NewListOrdersUseCase(db *sql.DB) *usecase.ListOrdersUseCase {
	repo := database.NewOrderRepository(db)
	return usecase.NewListOrdersUseCase(repo)
}

func NewCreateOrderUseCase(db *sql.DB) *usecase.CreateOrderUseCase {
	repo := database.NewOrderRepository(db)
	return usecase.NewCreateOrderUseCase(repo)
}

func NewWebOrderHandler(db *sql.DB) *web.WebOrderHandler {
	repo := database.NewOrderRepository(db)
	list := usecase.NewListOrdersUseCase(repo)
	create := usecase.NewCreateOrderUseCase(repo)
	return web.NewWebOrderHandler(list, create)
}
