// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	Customer    string  `json:"customer"`
	Description string  `json:"description"`
	Amount      float64 `json:"amount"`
}

type Mutation struct {
}

type Order struct {
	ID          string  `json:"id"`
	Customer    string  `json:"customer"`
	Description string  `json:"description"`
	Amount      float64 `json:"amount"`
	CreatedAt   string  `json:"createdAt"`
}

type Query struct {
}
