package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/rodrigocavalhero/clean_arch_orders_list/internal/infra/graph/model"
	"github.com/rodrigocavalhero/clean_arch_orders_list/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	if r.CreateOrderUseCase == nil {
		return nil, fmt.Errorf("create order: use case indisponível")
	}
	out, err := r.CreateOrderUseCase.Execute(ctx, usecase.CreateOrderInput{
		Customer:    input.Customer,
		Description: input.Description,
		Amount:      input.Amount,
	})
	if err != nil {
		return nil, err
	}
	o := out.Order
	return &model.Order{
		ID:          o.ID,
		Customer:    o.Customer,
		Description: o.Description,
		Amount:      o.Amount,
		CreatedAt:   o.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*model.Order, error) {
	if r.ListOrdersUseCase == nil {
		return nil, fmt.Errorf("list orders: use case indisponível")
	}
	out, err := r.ListOrdersUseCase.Execute(ctx, usecase.ListOrdersInput{})
	if err != nil {
		return nil, err
	}
	rows := make([]*model.Order, 0, len(out.Orders))
	for _, o := range out.Orders {
		rows = append(rows, &model.Order{
			ID:          o.ID,
			Customer:    o.Customer,
			Description: o.Description,
			Amount:      o.Amount,
			CreatedAt:   o.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		})
	}
	return rows, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
